App.Product = DS.Model.extend
	name: DS.attr('string')
	year: DS.attr('number')
	polyphony: DS.attr('number')
	desc: DS.attr('string')
	image: DS.attr('string')
	oscillator: DS.attr('string')
	revisions: DS.attr('string')
	waveform: DS.attr()
	control: DS.attr()
	exclusion: DS.attr()
	sampling: DS.attr()
	memory: DS.attr()
	sampler: DS.attr('boolean')
	synth: DS.attr('boolean')
	drum: DS.attr('boolean')
	productentries: DS.hasMany('productentry')
	productprices: DS.hasMany('productprice')
	company: DS.belongsTo('company')
	