development:
  adapter: postgresql
  encoding: unicode
  database: syn_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: syn_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: syn_production
  pool: 5
  username: postgres
  password: postgres
